### ISSUE TITLE
Could you provide an example with authentication?

### ISSUE THREAD

**Issue by gregveres** [ivaylokenov/MyTested.HttpServer#8]
I am testing my site that requires authentication. I have successfully queried the server and returned the login page. I have used AngleSharp to parse the html and verify that the input fields are there and have the proper types. 

Now the next step is to actually log in so I can stat to get some other pages and do similar verification. But I haven't seen any examples of how to log in. My app is an MVC application and has a Web API 2.0 api, but the Web API doesn't expose /token (not quite sure why). My Web API uses the same authentication as the MVC app. 

Any guidance would be very much appreciated. 

Thanks
Greg

**Comment by gregveres** [comment]
I have dug into this a bit more. Our app is using cookie authentication, not OAuth2's token based authentication. Do you have a suggestion of how to login with cookie auth?

Thanks
Greg

**Comment by ivaylokenov** [comment]
@gregveres You will need to login with the form collection on the HTTP request (or maybe first register an user) and save the cookie by using `AndProvideTheHttpResponseMessage` method. Then you can add that cookie in the every request you want the a logged int user. If it is not clear, I can add a sample for you?

**Comment by gregveres** [comment]
Ok that was the path I am going down. Since this is MVC, and I am using the anti-forgery token, I have to request the login page, pull out the anti-forgery token from the input field and the other anti-forgery token from the cookie. 
Then I have to send them back in the form post of the login page. 
Then I have to pull out the cookies that are returned and use them in my subsequent requests. 

I have done all of this but when I try to send the cookies back in a subsequent request they aren't getting set properly because I get the login page again. I am not sure I am dealing with the cookies header properly. 

```
        [Fact]
        public void LoginPageShouldAllowLogin()
        {
            string verificationToken = null;
            string cookieValue = null;

           // Get the login page to get the anti-forgery token and cookie
            var loginResponse = httpServer
                .WithHttpRequestMessage(req => req.WithMethod(HttpMethod.Get))
                .ShouldReturnHttpResponseMessage()
                .WithContent(html =>
                {
                    var parser = new HtmlParser();
                    var document = parser.Parse(html);

                    var tokenInput = (IHtmlInputElement)document.QuerySelectorAll("input").First();
                    Assert.Equal(tokenInput.Name, "__RequestVerificationToken");
                    verificationToken = tokenInput.Value;
                })
                .AndProvideTheHttpResponseMessage();
            // Get the anti-forgery cookie 
            var cookie = loginResponse.Headers.FirstOrDefault(h => h.Key == "Set-Cookie");
            Match M = Regex.Match(cookie.Value.First(), string.Format("{0}=(?<value>.*?);", "__RequestVerificationToken"));
            cookieValue = (M.ToString().Split('=')[1]);

            // Now use those tokens to login to get the session cookie
            loginResponse = MyHttpServer
                .WorkingRemotely(BaseAddress)
                .WithHttpRequestMessage(req => req
                    .WithMethod(HttpMethod.Post)
                    .WithRequestUri("http://localhost:50446/Account/Login?ReturnUrl=%2FPlayer")
                    .WithFormUrlEncodedContent(new[]
                    {
                        new KeyValuePair<string, string>("Email", "brock.lee@sk1.com"),
                        new KeyValuePair<string, string>("Password", "********"),
                        new KeyValuePair<string, string>("RemeberMe", "true"),
                        new KeyValuePair<string, string>("__RequestVerificationToken", verificationToken),
                    })
                    .WithHeader("Cookie", "__RequestVerificationToken=" + cookieValue))
                .ShouldReturnHttpResponseMessage()
                .WithContent(html =>
                {
                    // just here for debugging so I can see what was returned
                    var parser = new HtmlParser();
                })
                .AndProvideTheHttpResponseMessage();

            // Get the cookie and set it as a default header
            cookie = loginResponse.Headers.FirstOrDefault(h => h.Key == "Set-Cookie");
            MyHttpServer
                .IsLocatedAt(BaseAddress)
                .WithDefaultRequestHeaders(new Dictionary<string, IEnumerable<string>>() { { "Set-Cookie", cookie.Value } });

            // Request a page that requires authorization to verify we are logged in
            MyHttpServer
                .WorkingRemotely(BaseAddress)
                .WithHttpRequestMessage(req => req
                    .WithMethod(HttpMethod.Get)
                    .WithRequestUri("/Player")
                    .WithHeaders(new Dictionary<string, IEnumerable<string>>() { { "Set-Cookie", cookie.Value } }))
                .ShouldReturnHttpResponseMessage()
                .WithContent(html =>
                {
                    // here for debugging to see what was returned  - this is the login page again
                    var parser = new HtmlParser();
                });

        }
    }
```

**Comment by gregveres** [comment]
Looking at this further one thing that seems strange is that when I log in with Chrome, I see the following cookies in the request for the page:
- .AspNet.ApplicationCookie
- ASP.NET_SessionId
- __RequestVerificationToken

but when I look at the response from my login using the above code, my set Cookie list has three 
entries:
- ASP.NET_SessionId
- ASP.Net_SessionId
- __RequestVerificationToken

Notice that the sessionId is listed twice with exactly the same values. I think I would have expected one of those session Ids to be the ApplicationCookie.

**Comment by ivaylokenov** [comment]
@gregveres I believe this is the problem here:

http://stackoverflow.com/a/13287224/4324501

I am not setting this value. Will upload a new verion of the package in a couple of hours.

**Comment by gregveres** [comment]
Ah I see. Thank you for the very quick response!
Your packages are great, BTW. I am just getting started with them, but I can see how valuable they will be. On a different note, I would love to talk about what parts of the API and MVC controllers should be tested using which parts of the test frameworks. If we can have that discussion, I could try writing up a guide for your Wiki.

**Comment by ivaylokenov** [comment]
@gregveres Of course. If you want to help with the wiki, I will be very thankful (and happy)! Thank you for nice words!

**Comment by gregveres** [comment]
@ivaylokenov are you also going to make that change in your MyTested.WebAPI project?

**Comment by ivaylokenov** [comment]
@gregveres MyTested.HttpServer is now updated and uploaded to NuGet. Let me know, if the new code works fine with your case. I wrote a test and the cookies are sent correctly. It is the last one here:

https://github.com/ivaylokenov/MyTested.HttpServer/blob/master/test/MyTested.HttpServer.Tests/BuildersTests/HttpResponseMessageTestBuilderTests.cs

As for the MyTested.WebApi project - I am currently updating it. Will be available soon.

**Comment by gregveres** [comment]
That's great. I will download and test in my environment too. 

I am not in a big rush for the WebAPI update. I am playing around with the HttpServer project first to do some integration tests.

Thank you very much for getting this fixed so quickly.

**Comment by ivaylokenov** [comment]
@gregveres Are the cookies resolved successfully now? If yes, I should close the issue. I updated the WebApi package too.

**Comment by gregveres** [comment]
No but I am skeptical that it updated the Nuget package correctly. I don't have HttpHeader:Cookie as something that can be resolved. Ah I seem to remember that VS has to be restarted to get intellisense to pick up new things after package updates. 

But when I am logging in, the response message only contains the sessionId (not duplicated now) but it doesn't include the application cookie. So I am installing fiddler to see if I can see what is being sent back and forth.

**Comment by gregveres** [comment]
Hmm something isn't working. To use Fiddler I had to switch to using my deployed test server, over https so that I could see the traffic (fiddler can't capture .Net traffic on localhost apparently). When I do this, I don't even get the first login attempt to pass. the server keeps coming back with the anti-forgery token could not be decrypted.  Still investigating but I have an appointment soon that will cause me to stop for the day.

**Comment by gregveres** [comment]
Ok, I figured out that problem (stupid hard code server path in my test). 
Still working on trying to figure out why it isn't logging me in.

**Comment by ivaylokenov** [comment]
@gregveres I will try it too and report here results.

**Comment by gregveres** [comment]
Fiddler is paying off. The test code is what I posted earlier in this thread. You can see that I request the root (/) path. Our system has a redirect from / -> /Player, but when you aren't authenticated, this redirects to /Accounts/login. So that first call should get a login page - and it does. 
I then extract the tokens / cookies from that page and login. This is the second call to MyHttpServer. 

Then I am expecting a logged in response where I can extract the application token - the token I need to pass back to each subsequent request. 

I am not getting that in the second response. 

Here is the sequence that I am seeing in Fiddler:

Because of the first test call:
302 HTTPS   skycourttest1.azurewebsites.net /  
302 HTTPS   skycourttest1.azurewebsites.net /Player  
200 HTTPS   skycourttest1.azurewebsites.net /Account/Login?ReturnUrl=%2FPlayer

Because of the second test call:
302 HTTPS   skycourttest1.azurewebsites.net /Account/Login?ReturnUrl=%2FPlayer
302 HTTPS   skycourttest1.azurewebsites.net /Player  
200 HTTPS   skycourttest1.azurewebsites.net /Account/Login?ReturnUrl=%2FPlayer

notice that the second test call tries to call /Account login, which, when successful redirects to /Player. But then when following the 302 to go /Player, we are no longer authorized because we don't send the right application token cookie. So that then redirects me to /Account/Login again. And Account/Login is the response that is being returned by MyTested.HttpServer so I never get a chance to get the Application Token cookie value.

**Comment by ivaylokenov** [comment]
@gregveres Well, guess what: http://stackoverflow.com/questions/14731980/using-httpclient-how-would-i-prevent-automatic-redirects-and-get-original-statu

AutoRedirects are done by the HttpClient. Will fix it, then test it,with real server then upload it again.

**Comment by ivaylokenov** [comment]
@gregveres Also I am adding an option to pass that HttpClientHandler to the server so that it can be totally configurable.

**Comment by ivaylokenov** [comment]
@gregveres Fixed. Download the latest update. This is the code I use and it authenticates correctly.

``` c#
var server = MyHttpServer.IsLocatedAt("http://bgcoder.com");

            string verificationToken = null;
            string cookieValue = null;

            var response = server
                .WithHttpRequestMessage(req => req
                    .WithMethod(HttpMethod.Get)
                    .WithRequestUri("/Account/Login"))
                .ShouldReturnHttpResponseMessage()
                .WithStatusCode(HttpStatusCode.OK)
                .WithContent(html =>
                {
                    var parser = new HtmlParser();
                    var document = parser.Parse(html);

                    var tokenInput = (IHtmlInputElement)document.QuerySelectorAll("input[name='__RequestVerificationToken']").First();
                    verificationToken = tokenInput.Value;
                })
                .AndProvideTheHttpResponseMessage();

            var cookie = response.Headers.FirstOrDefault(h => h.Key == "Set-Cookie");
            Match M = Regex.Match(cookie.Value.First(), string.Format("{0}=(?<value>.*?);", "__RequestVerificationToken"));
            cookieValue = (M.ToString().Split('=')[1]);

            response = server
                .WithHttpRequestMessage(req => req
                    .WithMethod(HttpMethod.Post)
                    .WithRequestUri("/Account/Login")
                    .WithFormUrlEncodedContent(new[]
                    {
                        new KeyValuePair<string, string>("UserName", "ivaylo.kenov"),
                        new KeyValuePair<string, string>("Password", "*******"),
                        new KeyValuePair<string, string>("__RequestVerificationToken", verificationToken),
                    })
                    .WithHeader("Cookie", "__RequestVerificationToken=" + cookieValue))
                .ShouldReturnHttpResponseMessage()
                .AndProvideTheHttpResponseMessage();

            cookie = response.Headers.FirstOrDefault(h => h.Key == "Set-Cookie");
            M = Regex.Match(cookie.Value.First(c => c.Contains("ApplicationCookie")), string.Format("{0}=(?<value>.*?);", ".AspNet.ApplicationCookie"));
            cookieValue = (M.ToString().Split('=')[1]);

            response = server
                .WithHttpRequestMessage(req => req
                    .WithMethod(HttpMethod.Post)
                    .WithRequestUri("/Contests/Practice/Index/1")
                    .WithHeader("Cookie", ".AspNet.ApplicationCookie=" + cookieValue))
                .ShouldReturnHttpResponseMessage()
                .WithContent(html =>
                {
                    // contains the authenticated HTML
                })
                .AndProvideTheHttpResponseMessage();
```

I am waiting for confirmation whether or not it worked correctly with your tests. These cookie and HTML parsings deserve a package of their own...

**Comment by gregveres** [comment]
@ivaylokenov  Yes that worked!

I was also able to move the WithHeader("Cookie" ... line to a WithDefaultRequestHeader("Cookie"...

and removed the WithHeader line and it worked. Now I am going to bundle that up as a Login action that will happen in the test setup and I am good to go. 

Thank you very much for tracking this down so quickly with me. 
I assume you will move the redirect change over to the WebAPI package as well.
